version: '3'
x-common-variables: &common-variables
  POSTGRES_PASSWORD: password
  POSTGRES_USER: user
  POSTGRES_DB: app
services:
  db:
    image: postgres:latest
    environment: *common-variables
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build: .
    environment:
      <<: *common-variables
      DATABASE: postgres
      SQL_HOST: db
      SQL_PORT: 5432
      RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
volumes:
  db-data: